services:
    rampeur_cookie_consents.twig_extension.cookie_consent:
        class: Rampeur\Bundle\CookieConsentBundle\Twig\Extension\CookieConsentExtension
        arguments:
            - '%rampeur_cookie_consent.config%'
        tags:
            - { name: twig.extension }
